### ISSUE TITLE
Unclear how to install cmake and ruby from opkg.

### ISSUE THREAD

**Issue by yaronyamit2000** [robseb/rsyocto#11]
Hi, thank you very much for rsyocto! it is great :)

It seems that opkg default configuration is incomplete.
opkg install\update does nothing.
I've read all the manual of openwrt, and it has been very difficult for me to understand how to configure the repository.
It will be very nice if you will explain how to use opkg in this distro.
please help me,
best regards.

**Comment by robseb** [comment]
During development I used [this guide](https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/package-manager-white-paper.pdf) to implement and test the *opkg*  package manager. You can consider it, as well. Important is only that you have HTTP URL to a compatible package (for instance ARMv7A version). 
Please inform the community about your process.
Be the way a cmake version is already installed.

Best regards, 
Robin Sebastian

**Comment by yaronyamit2000** [comment]
I got this output for executing 'which cmake'-

which: no cmake in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin)
