### ISSUE TITLE
Can i use rsYocto to create linux distro for De1-SoC?

### ISSUE THREAD

**Issue by tungdt113** [robseb/rsyocto#12]
Can i use rsYocto to create linux distro to De1-SoC? if can, could you tell me the way to do it?
thank you!

**Comment by robseb** [comment]
Yes, you can use your board. Then, you only need a Intel Quartus Prime Project with the HPS Configuration. You can use my Build script to generate your own Yocto flavor as described here: https://github.com/robseb/rsyocto/blob/rsYocto-1.04/doc/guides/7_customVersions.md

**Comment by Andy2No** [comment]
> Yes, you can use your board. Then, you only need a Intel Quartus Prime Project with the HPS Configuration. You can use my Build script to generate your own Yocto flavor as described here: https://github.com/robseb/rsyocto/blob/rsYocto-1.04/doc/guides/7_customVersions.md

Is it possible to make a rsYocto version for the DE1-SoC by starting with an image for one of the other Cyclone V SoC versions, and just replacing some files?  If so, which ones would need to be different?
