### ISSUE TITLE
Cant use opkg

### ISSUE THREAD

**Issue by monsieur7** [robseb/rsyocto#13]
DE10 Nano SOC
Cyclone V
when doing opkg update, nothing is happening 
What am I doing wrong?
Thanks for your answer
PS : rsyocto is awesome!
![image](https://user-images.githubusercontent.com/62158053/107969512-29bb4c80-6fb0-11eb-8f97-692c20db929f.png)

**Comment by robseb** [comment]
Hello monsieur7, 
we had someome with a simalar issue with opkg. 
Please check it out: #11 

Robin Sebastian

**Comment by monsieur7** [comment]
Hello robseb,
I checked out the issue but it doesn't give any clue on how to resolve the problem 
Can you check that Please,

monsieur7

**Comment by robseb** [comment]
Inside this issue I tried to explain that it is necessary to configure the opkg package manager with a list of Domains (URLs) to the packages servers where are the packages to download located. 
By default is no opkg package pre-installed or any server added to the known list. That means the command "opkg update" can not find or do anything. 

I hope I could help.

**Comment by monsieur7** [comment]
Ok, thanks for the tip, I just copied the config files from the sd-card image from terasic website. It works!
I'm closing the issue 
PS : thank you for responding so fast!
