### ISSUE TITLE
DE10-Nano - Project archive restoration failed in Quartus 21.1 (for both)

### ISSUE THREAD

**Issue by Andy2No** [robseb/rsyocto#18]
I've been able to restore the .qar archives for the DE0-Nano-SoC and the DE10-Standard, in Quartus 21.1, but not for the DE10-Nano.

For both DE10-Nano. .qar files, I get an error saying " Project archive restoration failed .." (see attached).

![qar restoration failed - Quartus 21 1](https://user-images.githubusercontent.com/8021302/168667455-32ad47e1-3e47-403f-a964-c9454b9cb2ea.gif)

The same thing happens in Quartus 15.1 and 17.1.  Which version of Quartus is most likely to work?

I'm wondering if it would be better to just zip the project folders, rather than use Quartus to archive them.  That way, we'd still have access to the individual files.

**Comment by Andy2No** [comment]
@robseb Do you still have the DE10- Nano project files in an unarchived form?

I'm referring to the .qar file here:

 rsyocto / fpga / DE0NANOrsyocto.qar 

https://github.com/robseb/rsyocto/blob/rsYocto-1.042/fpga/DE0NANOrsyocto.qar

and

 rsyocto / fpga / DE10NANO_NIOS.qar 

https://github.com/robseb/rsyocto/blob/rsYocto-1.042/fpga/DE10NANO_NIOS.qar

**Comment by robseb** [comment]
@Andy2, I have tested both Links. Both Quartus Archive Files c**an be imported without any issue with Quartus Prime 18.1 Standard and Lite**. I would assume a Quartus 21.1 installation or software issue on your side. Unfortunately, this is very easily possible with this 21.1 Lite release.

**Comment by Andy2No** [comment]
Thanks for checking, @robseb .  After downloading and installing Quartus Prime 18.1 Lite, I still got the same error.  It turns out it's caused by long path lengths, regardless of the version of Quartus.  

After moving the .qar files closer to the root of the drive I put them on, I can now import them in either 18.1 or 21.1.
