### ISSUE TITLE
rsyocto_SD_1042.zip - what is its purpose?

### ISSUE THREAD

**Issue by Andy2No** [robseb/rsyocto#21]
This probably ought to be a discussion, not an issue, but since there's no discussion tab, yet, I've put it here.

I mistakenly made a microSD card with rsyocto_SD_1042.zip in Rufus, and tried to boot my DE10-Standard with it.  That didn't work, and looking at the contents all I see are a couple of autorun files, on one FAT32 partition taking up the whole card.

Rufus processed the image without errors, and quite quickly.  I'm now waiting for it to do the same with rsYocto_1_042_DE10STD.zip, which is taking a lot longer, despite the zip being about half the size.

I can't find any mention of rsyocto_SD_1042.zip by searching with or without the ".zip" part.

**Comment by robseb** [comment]
@Andy2No, thanks for having interest in my work and for your feedback.

Naming conventions such as _DE10STD are used to identify the specific development board as noted [here](https://github.com/robseb/rsyocto/blob/rsYocto-1.042/doc/guides/1_Booting.md#create-a-bootable-sd-card). These zip-files can be used to create a bootable SD-Card. The SD-Card folder contains the development files of this Linux Distribution and allows in conjunction with my build system to create new custom versions. I tied to document it best as possible as you can find [here](https://github.com/robseb/rsyocto/blob/rsYocto-1.042/doc/guides/7_customVersions.md#understand-the-internal-folder-structure).

**Comment by Andy2No** [comment]
Thanks, @robseb 

Have you considered adding a Discussions tab?  Sorry if I've asked this before.  They're a useful way for users of a repo to share knowledge without necessarily pestering you about it.  They can be a good place to ask about something that doesn't qualify as an issue too, e.g. just asking for clarification on how to do something, or sharing an idea on how to do something.

I might have observations to share as a discussion, once I've got back up to speed.  For example, when I looked at using this repo for the DE10-Nano, a while ago, I found I could load new FPGA images by sending them via a terminal program (TeraTerm), and either loading them manually or having them automatically overwrite the standard image, as it boots up.  I found that easier than learning how to make up a new microSD card and it seemed a simpler way to iterate development of a new design - at least for me.

I've since forgotten some of the details, but I'll try to reproduce in on the DE10-Standard, and make some notes.   A discussion with the details in might be useful to someone else, but it definitely doesn't qualify as an issue.

**Comment by robseb** [comment]
Okay @Andy2No I have enabled the discussion feature within GitHub. I do have a Gitter Chat room, as well.

**Comment by Andy2No** [comment]
Excellent.  Thanks, @robseb 

I think I've seen that chat room, a while ago, but I'd forgotten it existed.  [EDIT:  I've found it, here: https://app.gitter.im/#/room/#rsyocto_community:gitter.im ]

The discussions tab is a good feature, anyway, and is immediately accessible from the repo.  I've used it in earlephilhower/arduino-pico quite often ( **https://github.com/earlephilhower/arduino-pico/discussions** )
