### ISSUE TITLE
Change the apache2 site

### ISSUE THREAD

**Issue by jmlarbaig** [robseb/rsyocto#8]
Hey robin, 

I would like to change the direction of the web page when I want to connect on my board. Definitively, change the index page by my app Django. I searched long time how to change the direction of apache but I didn't find. 

Do you know how can I change ?

Best regards,

**Comment by robseb** [comment]
Hey Jean-Marie,

Yes, that no problem. They are two ways possible:
1. During runtime: Copy your "index.html"-file to following rootfs location: /usr/share/apache2/default-site/htdocs
2. With my build script: You can copy the "index.html" file into the "my_homepage" folder to create your own rsYocto image with your Django project pre-installed, as I mentioned: https://github.com/robseb/rsyocto/blob/rsYocto-1.03/doc/guides/6_newFPGAconf.md

Stay healthy,
Robin

**Comment by jmlarbaig** [comment]
Yes I saw your second option but I don't want to remake a linux image for
the moment. I will try the first option!
Thanks !
Larbaig Jean-Marie
PhD | SIAME Laboratory | High Power Process
mobile: 06.46.80.01.62
email: jeanmarie.larbaig@gmail.com
address: 2 Avenue Pierre Angot, 64000 Pau



Le jeu. 19 mars 2020 à 22:48, Robin Sebastian <notifications@github.com> a
écrit :
