### ISSUE TITLE
Adding OpenCL support to the build

### ISSUE THREAD

**Issue by kutenai** [robseb/rsyocto#9]
**Is your feature request related to a problem? Please describe.**
Looking for an up-to-date and well-documented build process for OpenCL development on Cyclone and Arria10 boards.

**Describe the solution you'd like**
It would be great to have an option to include the OpenCL build tools, as well as a reference OpenCL hardware project to start with.

**Describe alternatives you've considered**
I've looked at many other solutions, but all of them seem a bit out of date or lacking in some features. This one has up-to-date builds but lacks OpenCL

**Additional context**
None

**For witch Board/ Device ? **
*Arria10* and/or Cyclone V
I am specifically using a DE10-Nano, but have a CriticalLink VDK as well.

**Comment by robseb** [comment]
I' sorry I can see here an issue! 
In case you will ask me for the interation of OpenCL to me embedded Linux. It is not schedlued on my side. I know it is really painfully to get OpenCL running. I worked with that stuff, as well. However, I'm open for the community to design a integration and documentation for it. 
In this case we should use a other comunication way. 
Regards
Robin Sebastian

Best

**Comment by kutenai** [comment]
I appreciate the response. Yes, it is painful. I can understand the time 
limitations.
I will do my best.
